[[grep]]
arch = "aarch64"
git-tree-sha1 = "9a1f0709c255cc0d6e79755a44ecee653f943858"
os = "macos"

    [[grep.download]]
    sha256 = "7117dda28b59984ca0a1b4e92a1b5d3dd5bb21a75c403758f932b3c4eb825fbe"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.aarch64-apple-darwin.tar.gz"
[[grep]]
arch = "aarch64"
git-tree-sha1 = "0605081c507d26ce3dae6df97821649b4875fe5c"
libc = "glibc"
os = "linux"

    [[grep.download]]
    sha256 = "d296f9361a4ae58c5e747d566a9690219e70b58addb3511410b1e8f8d1c13eb6"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.aarch64-linux-gnu.tar.gz"
[[grep]]
arch = "aarch64"
git-tree-sha1 = "1b352653b95844d9fe450ca9808115c14d263df8"
libc = "musl"
os = "linux"

    [[grep.download]]
    sha256 = "f3210a1fd417a337631ea93d8f0f92a67d521fd150adf7e97e4ffaac567c9376"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.aarch64-linux-musl.tar.gz"
[[grep]]
arch = "aarch64"
git-tree-sha1 = "e144075a303f3da6fd975af5bd046665101c2625"
os = "freebsd"

    [[grep.download]]
    sha256 = "eada19e10e11e64cc2429bd4ae052483bc06e33d2b3b93c95b6d4b9ab653dccd"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.aarch64-unknown-freebsd.tar.gz"
[[grep]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b035e60ae1950cd874e3d9cabfe5e77d243e05f7"
libc = "glibc"
os = "linux"

    [[grep.download]]
    sha256 = "327deabd818f0f6fa5f4379b56b64d610d9995d57e74db24788866437b15c83f"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.armv6l-linux-gnueabihf.tar.gz"
[[grep]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bdbc3190d3e9b324f64c3807aecd4d2acb60f671"
libc = "musl"
os = "linux"

    [[grep.download]]
    sha256 = "7f4fa90fc769dadae2d8270ce832e15479c065b918ae3c308a67b0cf3b3df2fa"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.armv6l-linux-musleabihf.tar.gz"
[[grep]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b16be089480818223b1b15d78501ad83c2048a92"
libc = "glibc"
os = "linux"

    [[grep.download]]
    sha256 = "77f5c67e5c6632e866f7c7baa39745b0a7b3d2fb076e63b98a3fccc58cb06c7c"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.armv7l-linux-gnueabihf.tar.gz"
[[grep]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51720b782f7c27f9e8e6987a116a46cd8e0181a5"
libc = "musl"
os = "linux"

    [[grep.download]]
    sha256 = "ebc2b77bbeb48e2bce44e442bcdb41d4a707b94014e8ed86d01d452910a1697e"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.armv7l-linux-musleabihf.tar.gz"
[[grep]]
arch = "i686"
git-tree-sha1 = "db42398afa0ecc83eaf4cb30a98b2120d39e99c7"
libc = "glibc"
os = "linux"

    [[grep.download]]
    sha256 = "5b867f1c7327a44cd8da7bfaf011a27a131c821ddd4218f500393bfae35a1ce8"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.i686-linux-gnu.tar.gz"
[[grep]]
arch = "i686"
git-tree-sha1 = "061895855dc8a1bebb436a61a71eb9b7dc5dfe25"
libc = "musl"
os = "linux"

    [[grep.download]]
    sha256 = "9408f8112380f7498a7c9f6f93973e8683c2fc08d2b54bcc9de94f1d9942eb4c"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.i686-linux-musl.tar.gz"
[[grep]]
arch = "i686"
git-tree-sha1 = "dbf23c7ca5aeffa8f76d7218220d587c862f8ffa"
os = "windows"

    [[grep.download]]
    sha256 = "7a2328d747334107616736065d680d8c0be2c374b310cfa0ccd5ece906b88f0c"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.i686-w64-mingw32.tar.gz"
[[grep]]
arch = "powerpc64le"
git-tree-sha1 = "1e28886339f3c370a025b8956c3c25f5fd320982"
libc = "glibc"
os = "linux"

    [[grep.download]]
    sha256 = "2c1cc71a173f03c3f8944347f5c2027611b581c7ad7df451e8246539e046d3cc"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.powerpc64le-linux-gnu.tar.gz"
[[grep]]
arch = "riscv64"
git-tree-sha1 = "754cef3d9de2026cfbfc92c7fab3dc1060a8da17"
libc = "glibc"
os = "linux"

    [[grep.download]]
    sha256 = "c99ffd47f5c74cf352e36ee6eb517cd64670ad4cef05f52636073d1fade72d2d"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.riscv64-linux-gnu.tar.gz"
[[grep]]
arch = "x86_64"
git-tree-sha1 = "935972dbdc75c2edc3b5f95d9843cb216ea111a2"
os = "macos"

    [[grep.download]]
    sha256 = "c1d1cd5d5284254760b980cf2a81cc1cd3d3351dc009e5ba5dbdc4c9ba666439"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.x86_64-apple-darwin.tar.gz"
[[grep]]
arch = "x86_64"
git-tree-sha1 = "caecf8c88f06a67bdf825ee249aa6704770d9542"
libc = "glibc"
os = "linux"

    [[grep.download]]
    sha256 = "d165bb3d4c12c39cfd76022c137ee8fec86dbb99928a05b6ff91bc36950adb34"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.x86_64-linux-gnu.tar.gz"
[[grep]]
arch = "x86_64"
git-tree-sha1 = "2bbf6c048eb56ba26757607314dc28894b9ae980"
libc = "musl"
os = "linux"

    [[grep.download]]
    sha256 = "b5f523286cc3593a9807b40f29deda41ea962ac699f85ec681cd362e4c9066b2"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.x86_64-linux-musl.tar.gz"
[[grep]]
arch = "x86_64"
git-tree-sha1 = "0cf036cb7009c3bba2c26e80f8cf64249e99dd6d"
os = "freebsd"

    [[grep.download]]
    sha256 = "759f089637660b3f905bf6adfcf4127c4b29212bbfb597e6e6ed62979ec38256"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.x86_64-unknown-freebsd.tar.gz"
[[grep]]
arch = "x86_64"
git-tree-sha1 = "7a782cd0cf1e0f4fb0742cf0922afa64db055f5d"
os = "windows"

    [[grep.download]]
    sha256 = "b9d24d26991ce3192e15a04f6bc90788c72c8482d90f2dad7c15d38a9e028374"
    url = "https://github.com/JuliaBinaryWrappers/grep_jll.jl/releases/download/grep-v3.12.0+0/grep.v3.12.0.x86_64-w64-mingw32.tar.gz"
